export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const LOGOUT = "LOGOUT";

export const UPDATE_PRODUCTS = "UPDATE_PRODUCTS";
export const UPDATE_CART = "UPDATE_CART";
